/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#fce9c8",
        "error": "#9f403d",
        "primary-fixed": "#e5e2e1",
        "surface-tint": "#5f5e5e",
        "on-secondary-container": "#644f00",
        "inverse-primary": "#ffffff",
        "surface": "#f9f9f9",
        "on-tertiary": "#fff8f0",
        "error-dim": "#4e0309",
        "surface-dim": "#d4dbdd",
        "surface-container-high": "#e4e9ea",
        "on-background": "#2d3435",
        "inverse-surface": "#0c0f0f",
        "on-error": "#fff7f6",
        "tertiary-dim": "#5e5239",
        "on-surface-variant": "#5a6061",
        "primary-fixed-dim": "#d6d4d3",
        "tertiary": "#6b5d44",
        "primary-container": "#e5e2e1",
        "on-tertiary-container": "#62553c",
        "secondary": "#745c00",
        "background": "#f9f9f9",
        "secondary-fixed": "#ffe088",
        "on-surface": "#2d3435",
        "on-tertiary-fixed": "#4f432b",
        "tertiary-fixed-dim": "#eddbba",
        "secondary-dim": "#665100",
        "outline-variant": "#adb3b4",
        "on-tertiary-fixed-variant": "#6c5f45",
        "on-primary": "#faf7f6",
        "secondary-fixed-dim": "#f8d056",
        "tertiary-container": "#fce9c8",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#705900",
        "on-primary-fixed-variant": "#5c5b5b",
        "on-error-container": "#752121",
        "outline": "#757c7d",
        "surface-bright": "#f9f9f9",
        "surface-container-highest": "#dde4e5",
        "error-container": "#fe8983",
        "inverse-on-surface": "#9c9d9d",
        "primary-dim": "#535252",
        "on-primary-fixed": "#403f3f",
        "surface-container": "#ebeeef",
        "secondary-container": "#ffe088",
        "on-primary-container": "#525151",
        "surface-container-low": "#f2f4f4",
        "on-secondary": "#fff8ef",
        "primary": "#5f5e5e",
        "surface-variant": "#dde4e5",
        "on-secondary-fixed": "#4e3d00"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Manrope"],
        "label": ["Manrope"],
        "manrope": ["Manrope"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
}
